# -*- coding: utf-8 -*-
"""
/***************************************************************************
 layer_seperator
                                 A QGIS plugin
 Plugin to create seperate layers for different object types out of Survey2GIS outputs.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-07-03
        copyright            : (C) 2023 by heph/ArchFL
        email                : philipp.heidegger@llv.li
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load layer_seperator class from file layer_seperator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .layer_cleanup import layer_seperator
    return layer_seperator(iface)
